(local/package-install 'yaml-mode)
(local/package-install 'toml-mode)
(local/package-install 'markdown-mode)
(local/package-install 'pkgbuild-mode)
(local/package-install 'stumpwm-mode)
(local/package-install 'dockerfile-mode)
(local/package-install 'protobuf-mode)
(local/package-install 'thrift)
